---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint .
driver:
  name: docker
platforms:
  - name: instance
    image: "ricsanfre/docker-${MOLECULE_DISTRO:-ubuntu}-ansible:${MOLECULE_RELEASE:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    privileged: true
    pre_build_image: true
    exposed_ports:
      - 8200/tcp
      - 8201/tcp
    published_ports:
      - 0.0.0.0:8200:8200/tcp
      - 0.0.0.0:8201:8201/tcp
provisioner:
  name: ansible
  env:
    ANSIBLE_REMOTE_TMP: /tmp/.ansible/tmp
    ANSIBLE_LOCAL_TEMP: /tmp/.ansible/tmp
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible/tmp
      local_tmp: /tmp/.ansible/tmp
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
